Summary: dummy RPM
Name: dummy
Version: 1 
Release: 1 
License: GPL
Group: Development/Languages

%description 
dummy RPM to get RPM environment variables (BUILD and SRC)

%prep

file=/tmp/rpm_env
echo '# this file is generated by using rpm -bp rpm_env.spec' >$file
echo RPM_BUILD_DIR=%{_builddir}    >>$file
echo RPM_RPMS_DIR=%{_rpmdir}       >>$file
echo RPM_SOURCES_DIR=%{_sourcedir} >>$file
echo RPM_SPECS_DIR=%{_specdir}     >>$file
echo RPM_SRPMS_DIR=%{_srcrpmdir}   >>$file
echo RPM_DOC_DIR=%{_docdir}        >>$file
echo ARCH=%{_target_cpu}           >>$file

